[default.extend-words]
# Julia-specific functions
indexin = "indexin"
findfirst = "findfirst"
findlast = "findlast"
eachindex = "eachindex"
setp = "setp"
getp = "getp"
setu = "setu"
getu = "getu"

# Mathematical/scientific terms
jacobian = "jacobian"
hessian = "hessian" 
eigenvalue = "eigenvalue"
eigenvector = "eigenvector"
discretization = "discretization"
linearization = "linearization"
parameterized = "parameterized"
discretized = "discretized"
vectorized = "vectorized"

# Common variable patterns in Julia/SciML
ists = "ists"
ispcs = "ispcs"
osys = "osys"
rsys = "rsys"
usys = "usys"
fsys = "fsys"
eqs = "eqs"
rhs = "rhs"
lhs = "lhs"
ode = "ode"
pde = "pde"
sde = "sde"
dde = "dde"
bvp = "bvp"
ivp = "ivp"

# Common abbreviations
tol = "tol"
rtol = "rtol"
atol = "atol"
idx = "idx"
jdx = "jdx"
prev = "prev"
curr = "curr"
init = "init"
tmp = "tmp"
vec = "vec"
arr = "arr"
dt = "dt"
du = "du"
dx = "dx"
dy = "dy"
dz = "dz"

# Algorithm/type suffixes
alg = "alg"
prob = "prob"
sol = "sol"
cb = "cb"
opts = "opts"
args = "args"
kwargs = "kwargs"

# Scientific abbreviations
ND = "ND"
nd = "nd"
MTK = "MTK"
ODE = "ODE"
PDE = "PDE"
SDE = "SDE"
