"""
ConvergenceSimulation

A type which holds the data from a convergence simulation.

### Fields

* `solutions::Array{<:DESolution}`: Holds all the PdeSolutions.
* `errors`: Dictionary of the error calculations. Can contain:

    - `h1Errors`: Vector of the H1 errors.
    - `l2Errors`: Vector of the L2 errors.
    - `maxErrors`: Vector of the nodal maximum errors.
    - `node2Errors`: Vector of the nodal l2 errors.

* `N`: The number of simulations.
* `auxdata`: Auxillary data of the convergence simluation. Entries can include:

    - `Δts`: The Δt's in the simulations.
    - `Δxs`: The Δx's in the simulations.
    - `μs`: The CFL μ's in the simulations.
    - `νs`: The CFL ν's in the simulations.

* `𝒪est`: Dictionary of order estimates. Can contain:

    - `ConvEst_h1`: The H1 error order of convergence estimate for the convergence simulation.
       Generated via `log2(error[i+1]/error[i])`. Thus only valid if generated by halving/doubling
       the Δt/Δx. If alternate scaling, modify by dividing of log(base,ConvEst_h1)
    - `ConvEst_l2`: The L2 error order of convergence estimate for the convergence simulation.
       Generated via `log2(error[i+1]/error[i])`. Thus only valid if generated by halving/doubling
       the Δt/Δx. If alternate scaling, modify by dividing of log(base,ConvEst_l2)
    - `ConvEst_max`: The nodal maximum error order of convergence estimate for the convergence simulation.
       Generated via `log2(error[i+1]/error[i])`. Thus only valid if generated by halving/doubling
       the Δt/Δx. If alternate scaling, modify by dividing of log(base,ConvEst_max)
    - `ConvEst_node2`: The nodal l2 error order of convergence estimate for the convergence simulation.
       Generated via `log2(error[i+1]/error[i])`. Thus only valid if generated by halving/doubling
       the Δt/Δx. If alternate scaling, modify by dividing of log(base,ConvEst_node2)

* `convergence_axis`: The axis along which convergence is calculated. For example, if
   we calculate the Δt convergence, convergence_axis is the Δts used in the calculation.
"""
type ConvergenceSimulation{SolType<:DESolution}
  solutions::Array{SolType}
  errors
  N
  auxdata
  𝒪est
  convergence_axis
end

function ConvergenceSimulation(solutions,convergence_axis;auxdata=nothing)
  N = size(solutions,1)
  uEltype = eltype(solutions[1].u)
  errors = Dict() #Should add type information
  for k in keys(solutions[1].errors)
    errors[k] = reshape(uEltype[sol.errors[k] for sol in solutions],size(solutions)...)
  end
  𝒪est = Dict(map(calc𝒪estimates,errors))
  𝒪esttmp = Dict() #Makes Dict of Any to be more compatible
  for (k,v) in 𝒪est
    if length(v)==1 push!(𝒪esttmp,Pair(k,v[1]))
    else push!(𝒪esttmp,Pair(k,v))
    end
  end
  𝒪est = 𝒪esttmp
  return(ConvergenceSimulation(solutions,errors,N,auxdata,𝒪est,convergence_axis))
end

"""
test_convergence(Δts::AbstractArray,prob::SDEProblem)

Tests the strong order time convergence of the given algorithm on the given problem
solved over the given Δts.

### Keyword Arguments

* `T`: The final time. Default is 1
* `numMonte`: The number of simulations for each Δt. Default is 10000.
* `save_timeseries`: Denotes whether to save at every timeseries_steps steps. Default is true.
* `timeseries_steps`: Denotes the steps to save at if `save_timeseries=true`. Default is 1
* `alg`: The algorithm to test. Defaults to "EM".
"""
function test_convergence(Δts::AbstractArray,prob::SDEProblem;tspan=[0,1],numMonte=10000,save_timeseries=true,timeseries_steps=1,adaptive=false,kwargs...)
  N = length(Δts)
  #solutions = DESolution[solve(prob::SDEProblem,Δts[i],T,save_timeseries=save_timeseries,alg=alg) for j=1:numMonte,i=1:N]
  is = repmat(1:N,1,numMonte)'
  solutions = pmap((i)->solve(prob,tspan;Δt=Δts[i],save_timeseries=save_timeseries,timeseries_steps=timeseries_steps,adaptive=adaptive,kwargs...),is)
  solutions = convert(Array{SDESolution},solutions)
  solutions = reshape(solutions,numMonte,N)
  auxdata = Dict("Δts" =>  Δts)
  ConvergenceSimulation(solutions,Δts,auxdata=auxdata)
end

"""
test_convergence(Δts::AbstractArray,prob::ODEProblem)

Tests the order of the time convergence of the given algorithm on the given problem
solved over the given Δts.

### Keyword Arguments

* `T`: The final time. Default is 1
* `save_timeseries`: Denotes whether to save at every timeseries_steps steps. Default is true.
* `timeseries_steps`: Denotes the steps to save at if `save_timeseries=true`. Default is 1
* `alg`: The algorithm to test. Defaults to "Euler".
* `tableau`: The tableau used for generic methods. Defaults to ODE_DEFAULT_TABLEAU.
"""
function test_convergence(Δts::AbstractArray,prob::ODEProblem;tspan=[0,1],save_timeseries=true,adaptive=false,kwargs...)
  N = length(Δts)
  solutions = [solve(prob::ODEProblem,tspan;Δt=Δts[i],save_timeseries=save_timeseries,adaptive=adaptive,kwargs...) for i=1:N]
  auxdata = Dict(:Δts =>  Δts)
  ConvergenceSimulation(solutions,Δts,auxdata=auxdata)
end

"""
test_convergence(Δts::AbstractArray,Δxs::AbstractArray,prob::HeatProblem,convergence_axis)

Tests the convergence of the solver algorithm on the given Heat problem with
the Δts and Δxs as given. Uses the square mesh [0,1]x[0,1]. The convergence
axis is the axis along which convergence is calculated. For example, when testing
Δt convergence, `convergence_axis = Δts`.

### Keyword Arguments

* `T`: The final time. Defaults to 1
* `alg`: The algorithm to test. Default is "Euler".
"""
function test_convergence(Δts::AbstractArray,Δxs::AbstractArray,prob::HeatProblem,convergence_axis;T=1,alg=:Euler)
  if length(Δts)!=length(Δxs) error("Lengths of Δts!=Δxs. Invalid convergence simulation") end
  solutions = [solve(parabolic_squaremesh([0 1 0 1],Δxs[i],Δts[i],T,:dirichlet),prob,alg=alg) for i in eachindex(Δts)]
  auxdata = Dict(
            :Δts => [sol.fem_mesh.Δt for sol in solutions],
            :Δxs => [sol.fem_mesh.Δx for sol in solutions],
            :Δμs => [sol.fem_mesh.μ  for sol in solutions],
            :Δνs => [sol.fem_mesh.ν  for sol in solutions])
  return(ConvergenceSimulation(solutions,convergence_axis,auxdata=auxdata))
end

"""
test_convergence(Δxs::AbstractArray,prob::PoissonProblem)

Tests the convergence of the solver algorithm on the given Poisson problem with
Δxs as given. Uses the square mesh [0,1]x[0,1].

### Keyword Arguments

* `solver`: Which solver to use. Default is "Direct".
"""
function test_convergence(Δxs::AbstractArray,prob::PoissonProblem)
  solutions = [solve(notime_squaremesh([0 1 0 1],Δxs[i],:dirichlet),prob,solver=:Direct) for i in eachindex(Δxs)]
  auxdata = Dict("Δxs" => [sol.fem_mesh.Δx for sol in solutions])
  return(ConvergenceSimulation(solutions,Δxs,auxdata=auxdata))
end



"""
calc𝒪estimates(error::Vector{Number})

Computes the pairwise convergence estimate for a convergence test done by
halving/doubling stepsizes via

log2(error[i+1]/error[i])

Returns the mean of the convergence estimates
"""
function calc𝒪estimates(error::Pair)
  key = error.first
  error =error.second
  if ndims(error)>1 error=mean(error,1) end
  S = Vector{eltype(error)}(length(error)-1)
  for i=1:length(error)-1
    S[i] = log2(error[i+1]/error[i])
  end
  return(Pair(key,abs.(mean(S,1))))
end

"""
length(simres::ConvergenceSimulation)

Returns the number of simultations in the Convergence Simulation
"""
Base.length(sim::ConvergenceSimulation) = sim.N
Base.endof( sim::ConvergenceSimulation) = length(sim)
Base.getindex(sim::ConvergenceSimulation,i::Int) = sim.solutions[i]
Base.getindex(sim::ConvergenceSimulation,i::Int,I::Int...) = sim.solutions[i][I]

function print(io::IO, sim::ConvergenceSimulation)
  println(io,"$(typeof(sim)) of length $(length(sim)).")
  print(io,"Convergence Estimates:")
  for (k,v) in sim.𝒪est
    print(" ($k,$v)")
  end
  println(io,"\n-----------Errors-----------")
  for (k,v) in sim.errors
    println(io,"$k: $v")
  end
end

function show(io::IO,sim::ConvergenceSimulation)
  println(io,"$(typeof(sim)) of length $(length(sim)).")
  print(io,"Convergence Estimates:")
  for (k,v) in sim.𝒪est
    print(io," ($k,$v)")
  end
end
