name: Typos Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  typos-check:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for typos
      uses: crate-ci/typos@master
      with:
        config: ./_typos.toml
